<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    /**
     * Page ID to make reference to non child page
     */
    const NO_PARENT_PAGE_ID = 1;

    public function findAllByUser($user, $router, $request)
    {
        $pages = [];
        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        if (is_object($user)) {
            $userId = $user->getId();
            $statement = $connection->prepare('
                SELECT  DISTINCT p.*
                FROM    page p
                        INNER JOIN page_action pa ON pa.page_id = p.id_page
                        INNER JOIN role_action ra ON ra.action_id = pa.action_id
                        INNER JOIN user_role ur ON ur.role_id = ra.action_id
                            OR ur.role_id = 4
                        INNER JOIN user u ON u.id = ur.user_id
                WHERE   (:id IS NULL
                            OR u.id = :id)
            ');
            $statement->bindValue('id', $userId);
        } else {
            $statement = $connection->prepare('
                SELECT  DISTINCT p.*
                FROM    page p
                        INNER JOIN page_action pa ON pa.page_id = p.id_page
                WHERE   pa.action_id = 4
            ');
        }

        $statement->execute();
        $result = $statement->fetchAll();

        if ($result) {
            $stringSeparator = '|';
            $strRouteNamesWithParams = $stringSeparator;
            $routes = $router->getRouteCollection();
            foreach ($result as $page) {
                $url = '';
                $visible = ((integer) $page['visible'] === 1);
                if ($visible) {
                    if ($page['url']) {
                        $url = $router->getContext()->getBaseUrl() . '/' . $request->getLocale() . $page['url'];
                    } else if ($page['route_name']) {
                        $pageRouteName = $routes->get($page['route_name']);
                        if ($pageRouteName) {
                            $routeHasParams = preg_match('/\{[^_locale]+\}/', $pageRouteName->getPattern());
                            if (!$routeHasParams) {
                                $url = $router->generate($page['route_name']);
                            }
                        }
                    }
                }
                $pages[] = array(
                    'idItem' => $page['id_page'],
                    'domId' => 'item-',
                    'name' => $page['name'],
                    'class' => '',
                    'parent' => ($page['page_parent_id'] == self::NO_PARENT_PAGE_ID
                        ? null : $page['page_parent_id']
                        ),
                    'role'  => null,
                    'url'  => $url,
                    'routeName'  => $page['route_name'],
                    'visible'  => $visible,
                );
            }
        }

        return $pages;
    }
}
