<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRoleRepository extends EntityRepository
{
    public function findByUserId($userId)
    {
        $pages = [];
        $em = $this->getEntityManager();
        $connection = $em->getConnection();

        $statement = $connection->prepare('
            SELECT  DISTINCT r.*
            FROM    user_role ur
                    INNER JOIN role r ON r.id_role = ur.role_id
            WHERE   ur.user_id = :id
        ');
        $statement->bindValue('id', $userId);

        $statement->execute();
        $result = $statement->fetchAll();
    }
}
